name: falling_blocks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2
  flame: ^1.22.0
  google_fonts: ^6.3.2
  flame_noise: ^0.1.1+9
  firebase_core: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AmaticSC
      fonts:
        - asset: fonts/AmaticSC-Bold.ttf
